name: python-ci

on: [ push, pull_request ]

jobs:
  build:
    name: Python ${{ matrix.python-version }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        working-directory: Server
        run: pip install -r requirements.ci.txt

      - name: Run tox
        working-directory: Server
        run: tox

      - name: Build
        working-directory: Server
        run: python -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: Server/dist
